apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mysql
resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml
  - demoapp.yaml
configMapGenerator:
  - name: mysqlconfig
    files:
      - my.cnf
