apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-mysql
resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml
# - demoapp.yaml
  - operator.yaml
images:
- name: quay.io/cybozu/mysql
  newName: quay.io/ishii_masayuki/mysql
  newTag: poc-01
configMapGenerator:
  - name: mysqlconfig
    files:
      - my.cnf
  - name: operator-script
    files:
      - script/setup.sh
      - script/do.sh
      - script/status.sh
  - name: operator-sql
    files:
      - sql/status.sql
