apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-mysql
resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml
# - demoapp.yaml
  - operator.yaml
configMapGenerator:
  - name: mysqlconfig
    files:
      - my.cnf
  - name: setup-sql
    files:
      - setup_master.sql
      - setup_slave.sql
  - name: setup-script
    files:
      - setup_cluster.sh
