apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-mysql
resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml
  - demoapp.yaml
configMapGenerator:
  - name: mysqlconfig
    files:
      - my.cnf

# To change the destination namespace, uncomment the following statement.
# And also change `namespace.yaml`.
# namespace: app-mysql-hoge
