apiVersion: v1
kind: Pod
metadata:
  name: operator
spec:
  containers:
  - name: operator
    image: quay.io/cybozu/mysql:latest
    command:
    - sleep
    args:
    - infinity
    securityContext:
      runAsUser: 10000
      runAsGroup: 10000
    volumeMounts:
    - mountPath: /etc/mysql/setup/sql
      name: sql-vol
    - mountPath: /etc/mysql/setup
      name: script-vol
    env:
    - name: MYSQLSH_USER_CONFIG_HOME
      value: /tmp
    - name: MYSQL_CLUSTER_DOMAIN
      value: my-app-db
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-app-db-root-password
          key: password
    - name: MYSQL_OPERATOR_USER
      valueFrom:
        secretKeyRef:
          name: my-app-db-secret
          key: operator-user
    - name: MYSQL_OPERATOR_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-app-db-secret
          key: operator-password
    - name: MYSQL_REPLICATION_USER
      valueFrom:
        secretKeyRef:
          name: my-app-db-secret
          key: replication-user
    - name: MYSQL_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-app-db-secret
          key: replication-password

  volumes:
  - name: script-vol
    configMap:
      name: operator-script
      defaultMode: 0755
  - name: sql-vol
    configMap:
      name: operator-sql
