apiVersion: v1
kind: Service
metadata:
  labels:
    v1alpha1.mysql.oracle.com/cluster: my-app-db
  name: my-app-db
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    v1alpha1.mysql.oracle.com/cluster: my-app-db
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    v1alpha1.mysql.oracle.com/cluster: my-app-db
  name: my-app-db-copy
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    is-copy: "true"
  sessionAffinity: None
  type: ClusterIP
