apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    v1alpha1.mysql.oracle.com/cluster: my-app-db
    v1alpha1.mysql.oracle.com/version: ikezoe-9aebcc37-dirty
  name: my-app-db
  namespace: mysql
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      v1alpha1.mysql.oracle.com/cluster: my-app-db
  serviceName: my-app-db
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        v1alpha1.mysql.oracle.com/cluster: my-app-db
    spec:
      containers:
      - command:
        - /bin/bash
        - -ecx
        - |2-

                   # Set baseServerID
                   base=1000

                   # Finds the replica index from the hostname, and uses this to define
                   # a unique server id for this instance.
                   index=$(cat /etc/hostname | grep -o '[^-]*$')
                   /entrypoint.sh --server_id=$(expr $base + $index) --datadir=/var/lib/mysql --user=mysql --gtid_mode=ON --enforce_gtid_consistency=ON --log-slave-updates=ON  --master-info-repository=TABLE --relay-log-info-repository=TABLE --transaction-write-set-extraction=XXHASH64 --relay-log=my-app-db-${index}-relay-bin --report-host="my-app-db-${index}.my-app-db"  --loose-group-replication-exit-state-action=READ_ONLY
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: my-app-db-root-password
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: MYSQL_LOG_CONSOLE
          value: "true"
        image: quay.io/ikezoe/mysql:8.0.19
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlvolume
          subPath: mysql
        - name: cm-volume
          mountPath: /etc/mysql
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/run/mysqld
          name: varrun
        - mountPath: /var/lib/mysql-files
          name: mysqlfiles
        - mountPath: /var/log/mysql
          name: mysqllogs
        - mountPath: /var/tmp/mysql
          name: tmpDir
      securityContext:
        runAsUser: 27
        runAsGroup: 27
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: varrun
      - emptyDir: {}
        name: mysqlfiles
      - emptyDir: {}
        name: mysqlvolume
      - emptyDir: {}
        name: mysqllogs
      # TODO: tmpDir volume should be replaced with ephemeral volume
      - emptyDir: {}
        name: tmpDir
      - emptyDir: {}
        name: mysqlbackupvolume
      - name: cm-volume
        configMap:
          name: mysqlconfig
  updateStrategy:
    type: RollingUpdate
