# original is https://github.com/oracle/mysql-operator/blob/9aebcc37a080283bdc199d7150d91f2e9bfa4e2c/examples/demo/wordpress-router/wordpress-deployment.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-router
  namespace: mysql
  labels:
    app: wordpress-router
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-router
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-router
  namespace: mysql
  labels:
    app: wordpress-router
spec:
  selector:
    matchLabels:
      app: wordpress-router
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-router
    spec:
      containers:
      - name: mysqlrouter
        image: mysql/mysql-router:8.0.19
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-app-db-root-password
              key: password
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_HOST
          value: my-app-db-0.my-app-db
        - name: MYSQL_INNODB_NUM_MEMBERS
          value: "3"
        command:
        - "/bin/bash"
        - "-cx"
        - "exec /run.sh mysqlrouter"
      - name: wordpress
        image: wordpress:4.9-php7.2-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:6446
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-app-db-root-password
              key: password
        ports:
        - containerPort: 80
